import Head from "next/head";
import { useState } from "react";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { abi, polygonAddress, shardeumAddress } from "@/constants";
import { useContract, useSigner, useNetwork, useAccount } from "wagmi";
import { ethers } from "ethers";
export default function Home() {
  const { data: signer, isError, isLoading } = useSigner();
  const { address, isConnected } = useAccount();
  const [show, setShow] = useState(false);
  const [num, setNum] = useState(0);
  const { chain } = useNetwork();

  const contract = useContract({
    abi,
    address: chain?.network === "maticmum" ? polygonAddress : shardeumAddress,
    signerOrProvider: signer,
  });

  const setNumber = async () => {
    try {
      const number = document.getElementById("number").value;
      const tx = await contract.setNumber(number);
      await tx.wait();
    } catch (e) {
      console.log(e, "setNumber error");
    }
  };

  const getNumber = async () => {
    try {
      const number = await contract.getNumber(address);
      setShow(true);
      setNum(number);
    } catch (e) {
      console.log(e, "getNumber error");
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row-reverse mx-20 my-5">
        <ConnectButton />
      </div>

      <div className="flex flex-col items-center gap-10">
        <div className="flex flex-col items-center gap-2">
          <input
            type="number"
            className="border-2 w-80 p-1 focus:outline-none"
            id="number"
          ></input>
          <button
            className="rounded-lg bg-blue-400 px-2 py-1"
            onClick={setNumber}
          >
            Set Number
          </button>
        </div>
        <div className="flex flex-col items-center gap-2">
          {show && (
            <p>Your favourite number is {ethers.utils.formatUnits(num, 0)}</p>
          )}
          <button
            className="rounded-lg bg-blue-400 px-2 py-1"
            onClick={getNumber}
          >
            Get Number
          </button>
        </div>
      </div>
    </>
  );
}
